DROP TABLE IF EXISTS `APP_CONTEXT`;
CREATE TABLE `APP_CONTEXT` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `SUBTITLE` varchar(100) DEFAULT NULL,
  `DETAILED` varchar(3000) DEFAULT NULL,
  `APP_PACKAGE` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `APP_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `VERSION_CODE` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(40) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` varchar(40) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `MODEDESC` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `GENERAL` tinyint(4) DEFAULT '1',
  `TYPE` tinyint(4) NOT NULL DEFAULT '0',
  `LANGUAGE` varchar(32) NOT NULL DEFAULT 'zh',
  PRIMARY KEY (`id`),
  KEY `idx_context_type_package` (`TYPE`,`APP_PACKAGE`) USING BTREE,
  KEY `idx_context_type_name` (`TYPE`,`APP_NAME`) USING BTREE,
  KEY `idx_context_type` (`TYPE`) USING BTREE,
  KEY `idx_context_type_package_l` (`TYPE`,`LANGUAGE`,`APP_PACKAGE`) USING BTREE,
  KEY `idx_context_type_name_l` (`TYPE`,`LANGUAGE`,`APP_NAME`) USING BTREE,
  KEY `idx_context_type_l` (`TYPE`,`LANGUAGE`) USING BTREE,
  KEY `idx_context_package_ver_title` (`APP_PACKAGE`,`VERSION_CODE`,`TITLE`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `APP_GAMEGIFT_CDKEY`;
CREATE TABLE `APP_GAMEGIFT_CDKEY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CDKEY` varchar(32) DEFAULT NULL,
  `GIFTTIME` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `APP_GAMEGIFT_GAMENAME`;
CREATE TABLE `APP_GAMEGIFT_GAMENAME` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GAMENAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `GIFTCONTENT` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_gamegift_gamename` (`GAMENAME`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `APP_GAMEGIFT_USER`;
CREATE TABLE `APP_GAMEGIFT_USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SN` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `CDKEY` varchar(32) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_gamegift_sn` (`SN`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `APP_GAMELIST`;
CREATE TABLE `APP_GAMELIST` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `APP_NAME` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `ICON_URL` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `URL` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `CREATED_BY` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `MODEDESC` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `GENERAL` tinyint(4) DEFAULT '1',
  PRIMARY KEY (`ID`),
  KEY `idx_app_geamelist_name` (`APP_NAME`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `APP_KEYORDER`;
CREATE TABLE `APP_KEYORDER` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `APP_NAME` varchar(32) DEFAULT NULL,
  `VERSION_CODE` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(1000) CHARACTER SET latin1 DEFAULT NULL,
  `CREATED_BY` varchar(40) CHARACTER SET latin1 DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` varchar(40) CHARACTER SET latin1 DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `APP_PACKAGE` varchar(200) CHARACTER SET latin1 DEFAULT NULL,
  `MODEDESC` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `ACCOUNT_NO` int(11) DEFAULT NULL,
  `DEVICE_SN` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `LAST_TIME` int(11) DEFAULT NULL,
  `DEVICE_CLASS` int(11) DEFAULT NULL,
  `WIDTH` int(11) DEFAULT NULL,
  `HEIGHT` int(11) DEFAULT NULL,
  `GENERAL` tinyint(4) DEFAULT NULL,
  `DEFAULT_KEY` int(11) DEFAULT NULL,
  `SCHEME_PLATFORM` int(11) DEFAULT NULL,
  `ORDER_ID` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_order_1` (`APP_PACKAGE`,`VERSION_CODE`,`DEVICE_CLASS`,`SCHEME_PLATFORM`,`ACCOUNT_NO`,`GENERAL`) USING BTREE,
  KEY `idx_order_2` (`APP_PACKAGE`,`DEVICE_CLASS`,`SCHEME_PLATFORM`,`ACCOUNT_NO`,`GENERAL`) USING BTREE,
  KEY `idx_order_3` (`APP_NAME`,`DEVICE_CLASS`,`SCHEME_PLATFORM`,`ACCOUNT_NO`,`GENERAL`) USING BTREE,
  KEY `idx_order_4` (`ACCOUNT_NO`,`APP_PACKAGE`,`VERSION_CODE`,`SCHEME_PLATFORM`,`ORDER_ID`) USING BTREE,
  KEY `idx_order_5` (`ACCOUNT_NO`,`APP_PACKAGE`,`VERSION_CODE`,`DEVICE_SN`,`SCHEME_PLATFORM`,`ORDER_ID`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `APP_KEYSCREEN`;
CREATE TABLE `APP_KEYSCREEN` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `APP_NAME` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `VERSION_CODE` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(10244) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CREATED_BY` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `APP_PACKAGE` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `EFFTIME` int(11) DEFAULT NULL,
  `MODEDESC` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `ACCOUNT_NO` int(11) DEFAULT '0',
  `DEVICE_SN` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `LAST_TIME` int(11) DEFAULT '0',
  `DEVICE_CLASS` int(11) NOT NULL DEFAULT '0',
  `WIDTH` int(11) NOT NULL DEFAULT '0',
  `HEIGHT` int(11) NOT NULL DEFAULT '0',
  `GENERAL` tinyint(4) DEFAULT '1',
  `ADAPTER_ID` varchar(32) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `JS_R_OFFSET` int(11) DEFAULT '0',
  `BACKGROUND_URL` varchar(200) COLLATE utf8_unicode_ci DEFAULT '',
  `HASH_CODE` int(11) DEFAULT '0',
  `ADAPTER_VER` varchar(32) COLLATE utf8_unicode_ci DEFAULT '1.0',
  PRIMARY KEY (`ID`),
  KEY `idx_keyscreen_vercode` (`VERSION_CODE`) USING HASH,
  KEY `idx_keyscreen_dsn` (`DEVICE_SN`) USING BTREE,
  KEY `ACCOUNT_NO` (`ACCOUNT_NO`),
  KEY `idx_keyscreen_package` (`APP_PACKAGE`) USING BTREE,
  KEY `idx_keyscreen_app_name` (`APP_NAME`) USING BTREE,
  KEY `idx_keyscreen_adapter_id` (`ADAPTER_ID`) USING BTREE,
  KEY `idx_keyscreen_hash_code` (`HASH_CODE`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `APP_KEYSCREEN_BLACKLIST`;
CREATE TABLE `APP_KEYSCREEN_BLACKLIST` (
  `BLACKLIST_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BLACKLIST_WORD` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`BLACKLIST_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `APP_SHARES`;
CREATE TABLE `APP_SHARES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SHARE_SN` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '0',
  `SHOW_URL` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `SHARE_TIME` varchar(32) DEFAULT '0',
  `KEYADAPTERS` varchar(10644) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `KEYORDERS` varchar(7500) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_app_shares_sn_time` (`SHARE_SN`,`SHARE_TIME`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `APP_SHOP_LIST`;
CREATE TABLE `APP_SHOP_LIST` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `WORD` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_app_shoplist_name` (`WORD`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `KEY_3D_SCHEME`;
CREATE TABLE `KEY_3D_SCHEME` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DEVICE_CLASS` varchar(32) NOT NULL,
  `DEVICE_SN` varchar(50) DEFAULT NULL,
  `APP_PACKAGE` varchar(200) DEFAULT NULL,
  `APP_NAME` varchar(50) NOT NULL,
  `VERSION_CODE` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
